### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sanraith** [sanraith/aoc2020#1]
- [x] Measure solution time
- [x] Show solution time on web
- [x] Show solution time on console
- [x] Show progress on web
- [x] Show progress on console
- [x] Support multi line results on web
- [x] Support multi line results on console
- [x] Handle parts together in solution worker
- [x] Fix tests
- [x] Start all solutions at once on web. (add progress bar within calendar)
- [x] Parameterize console runner
- [x] Update readme
- [x] Add summary paragraph to web (a.k.a. 'about' section)
- [x] Support visualizations
- [ ] Do not automatically re-download input if an existing day is re-scaffolded.

**Comment by Aneurysm9** [comment]
Please ensure that the input data is only requested once.  It will not change and thus the downloaded data should be treated as a cache with indefinite expiration.  Also, please do not copy the puzzle text.  All puzzle text is copyrighted and the property of Advent of Code, LLC.  No permission is granted to reproduce the puzzle text.

**Comment by sanraith** [comment]
@Aneurysm9 No worries, puzzle input is saved to FS and should be only be requested once now that the scaffolding logic is complete. I can add some additional checks, so that even re-scaffolding the same day does not automatically download the input again.

Regarding puzzle text:
I did not plan to use the puzzle descriptions, but I hope using just the title of each puzzle is okay?

**Comment by Aneurysm9** [comment]
Using the titles is probably fine, though obviously I cannot, and do not hereby, grant any license to the content.
